# Generated by Django 3.2.20 on 2024-06-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Неструктурированные данные', 'verbose_name_plural': 'Неструктурированные данные'},
        ),
        migrations.AddField(
            model_name='data',
            name='sep',
            field=models.CharField(default=';', max_length=1, verbose_name='Разделитель'),
        ),
    ]
