# Generated by Django 3.2.20 on 2024-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240608_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='timestamp',
            field=models.CharField(auto_created=True, default='20240608124847', max_length=20, verbose_name='Время загрузки'),
        ),
    ]
